---

default_stages: [push]
repos:
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.8
      stages: [commit]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.780
  #   hooks:
  #   - id: mypy
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: check-yaml
    -   id: debug-statements
        exclude: _pytest/(debugging|hookspec).py
        language_version: python3
  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.8.2
  #   hooks:
  #   -   id: flake8
  #       language_version: python3
  #       additional_dependencies: [flake8-typing-imports==1.9.0]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
    -   id: reorder-python-imports
        args: ['--application-directories=.:src', --py3-plus]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.4.4
    hooks:
    -   id: pyupgrade
        args: [--py3-plus]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: master
    hooks:
    - id: autopep8
      # stages: [push]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.780  # NOTE: keep this in sync with setup.cfg.
  #   hooks:
  #   -   id: mypy
  #       files: ^(src/|testing/)
  #       args: []
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
  #   rev: v1.0.4
  #   hooks:
  #   -   id: python-bandit-vulnerability-check
  #       # args: [-l, --recursive, -x, tests]
  #       files: .py$
  # - repo: local
  #   hooks:
  #     - id: tests
  #       name: run tests
  #       entry: pytest -v
  #       language: system
  #       types: [python]
  #       stages: [push]
